from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from meta_harness.proposers.base import ProposalEnvelope
from meta_harness.proposers.command_proposer import run_proposal_command


_DEFAULT_SYSTEM_PROMPT = (
    "You are an offline harness optimizer. Propose the smallest effective change "
    "that improves the objective while preserving stability."
)


@dataclass(slots=True)
class LLMHarnessProposer:
    proposer_id: str = "llm_harness"
    command: list[str] | None = None
    model_name: str | None = None
    system_prompt: str | None = None
    prompt_template: str | None = None
    extra_payload: dict[str, Any] = field(default_factory=dict)

    def propose(
        self,
        *,
        objective: dict[str, Any],
        experience: dict[str, Any],
        constraints: dict[str, Any],
    ) -> ProposalEnvelope:
        effective_config = dict(constraints.get("effective_config") or {})
        llm_config = self._llm_config(effective_config)
        command = self.command or llm_config.get("command")
        if not isinstance(command, list) or not command:
            raise ValueError(
                "llm_harness proposer requires optimization.llm_harness.command"
            )

        model_name = self.model_name or self._coerce_string(
            llm_config.get("model") or llm_config.get("model_name")
        )
        if not model_name:
            raise ValueError(
                "llm_harness proposer requires optimization.llm_harness.model"
            )

        system_prompt = (
            self.system_prompt
            or self._coerce_string(llm_config.get("system_prompt"))
            or _DEFAULT_SYSTEM_PROMPT
        )
        prompt_template = (
            self.prompt_template or self._coerce_string(llm_config.get("prompt_template"))
        )

        source_run_ids = [
            str(record.get("run_id"))
            for record in experience.get("matching_runs", [])
            if str(record.get("run_id") or "")
        ]
        user_prompt = self._build_user_prompt(
            objective=objective,
            experience=experience,
            constraints=constraints,
            template=prompt_template,
        )
        payload = {
            "profile": constraints.get("profile_name"),
            "project": constraints.get("project_name"),
            "model": model_name,
            "system_prompt": system_prompt,
            "user_prompt": user_prompt,
            "objective": objective,
            "experience": experience,
            "proposal_constraints": dict(constraints.get("proposal_constraints") or {}),
            "effective_config": effective_config,
            **self.extra_payload,
        }
        generated = run_proposal_command(
            command=[str(item) for item in command],
            payload=payload,
            effective_config=effective_config,
        )

        proposal = (
            generated.get("proposal")
            if isinstance(generated.get("proposal"), dict)
            else self._fallback_proposal(
                objective=objective,
                experience=experience,
                model_name=model_name,
            )
        )
        notes = str(
            generated.get(
                "notes",
                f"llm harness proposal generated by {model_name}",
            )
        )
        return {
            "proposer_kind": "llm_harness",
            "proposal": proposal,
            "config_patch": (
                generated.get("config_patch")
                if isinstance(generated.get("config_patch"), dict)
                else None
            ),
            "code_patch": (
                str(generated["code_patch"])
                if generated.get("code_patch") is not None
                else None
            ),
            "notes": notes,
            "source_run_ids": source_run_ids,
        }

    @staticmethod
    def _llm_config(effective_config: dict[str, Any]) -> dict[str, Any]:
        optimization = effective_config.get("optimization")
        if not isinstance(optimization, dict):
            return {}
        config = optimization.get("llm_harness")
        return dict(config) if isinstance(config, dict) else {}

    @staticmethod
    def _coerce_string(value: Any) -> str | None:
        if value is None:
            return None
        return str(value)

    def _build_user_prompt(
        self,
        *,
        objective: dict[str, Any],
        experience: dict[str, Any],
        constraints: dict[str, Any],
        template: str | None,
    ) -> str:
        if template:
            return template.format(
                objective=json.dumps(objective, ensure_ascii=False, indent=2),
                experience=json.dumps(experience, ensure_ascii=False, indent=2),
                constraints=json.dumps(constraints, ensure_ascii=False, indent=2),
            )

        matching_runs = experience.get("matching_runs", [])
        failure_records = experience.get("failure_records", [])
        best_candidate = experience.get("best_candidate") or {}
        lines = [
            "Objective:",
            json.dumps(objective, ensure_ascii=False, indent=2, sort_keys=True),
            "",
            "Experience Summary:",
            f"- matching_runs: {len(matching_runs)}",
            f"- failure_records: {len(failure_records)}",
        ]
        if isinstance(best_candidate, dict) and best_candidate.get("candidate_id"):
            lines.append(f"- best_candidate_id: {best_candidate['candidate_id']}")
        source_runs = [
            str(record.get("run_id"))
            for record in matching_runs
            if str(record.get("run_id") or "")
        ]
        if source_runs:
            lines.append(f"- source_run_ids: {', '.join(source_runs)}")
        families = [
            str(record.get("family") or record.get("signature") or "").strip()
            for record in failure_records
            if str(record.get("family") or record.get("signature") or "").strip()
        ]
        if families:
            lines.append(f"- failure_families: {', '.join(families[:5])}")
        lines.extend(
            [
                "",
                "Constraints:",
                json.dumps(
                    {
                        "profile_name": constraints.get("profile_name"),
                        "project_name": constraints.get("project_name"),
                        "focus": objective.get("focus"),
                        "proposal_constraints": constraints.get("proposal_constraints") or {},
                    },
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                ),
                "",
                "Return JSON with keys: proposal, config_patch, code_patch, notes.",
                "proposal should describe the intended harness change and rationale.",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _fallback_proposal(
        *,
        objective: dict[str, Any],
        experience: dict[str, Any],
        model_name: str,
    ) -> dict[str, Any]:
        matching_runs = experience.get("matching_runs", [])
        return {
            "strategy": "llm_harness_patch",
            "model": model_name,
            "objective": objective,
            "source_runs": [
                str(record.get("run_id"))
                for record in matching_runs
                if str(record.get("run_id") or "")
            ],
        }
