from __future__ import annotations

import pytest

from meta_harness.proposers import (
    BaseRegistryProposer,
    HeuristicProposer,
    LLMHarnessProposer,
    build_proposer,
    get_proposer,
    list_proposers,
    rank_proposals,
    register_proposer,
)


class _DummyProposer(BaseRegistryProposer):
    proposer_id = "dummy"

    def propose(self, **_: object) -> dict[str, object]:
        return {
            "proposer_kind": self.proposer_id,
            "proposal": {"strategy": "dummy"},
            "notes": "dummy proposal",
        }


def test_proposer_registry_supports_register_and_lookup() -> None:
    register_proposer(_DummyProposer())

    proposer = get_proposer("dummy")

    assert proposer.proposer_id == "dummy"
    assert "dummy" in list_proposers()


def test_rank_proposals_orders_by_score_stability_and_cost() -> None:
    ranked = rank_proposals(
        [
            {
                "proposal_id": "proposal-a",
                "proposal": {"strategy": "high-cost"},
                "proposal_score": 1.1,
                "stability_score": 0.4,
                "cost_score": 0.1,
            },
            {
                "proposal_id": "proposal-b",
                "proposal": {"strategy": "balanced"},
                "proposal_score": 1.0,
                "stability_score": 0.9,
                "cost_score": 0.9,
            },
        ]
    )

    assert ranked[0]["proposal_id"] == "proposal-b"
    assert ranked[0]["proposal_rank"] == 1
    assert ranked[0]["ranking_basis"]["weighted_total"] > ranked[1]["ranking_basis"]["weighted_total"]


def test_build_proposer_constructs_llm_harness_from_effective_config() -> None:
    proposer = build_proposer(
        "llm_harness",
        effective_config={
            "optimization": {
                "llm_harness": {
                    "command": ["python", "scripts/generate.py"],
                    "model": "gpt-test",
                    "system_prompt": "You are an optimizer.",
                }
            }
        },
    )

    assert isinstance(proposer, LLMHarnessProposer)
    assert proposer.command == ["python", "scripts/generate.py"]
    assert proposer.model_name == "gpt-test"
    assert proposer.system_prompt == "You are an optimizer."


def test_build_proposer_supports_comma_separated_multiple_proposers() -> None:
    proposers = build_proposer("heuristic,llm_harness", effective_config={})

    assert len(proposers) == 2
    assert isinstance(proposers[0], HeuristicProposer)
    assert isinstance(proposers[1], LLMHarnessProposer)


def test_llm_harness_proposer_requires_configured_command() -> None:
    proposer = LLMHarnessProposer()

    with pytest.raises(ValueError, match="llm_harness proposer requires"):
        proposer.propose(
            objective={"goal": "improve retrieval"},
            experience={},
            constraints={"effective_config": {}},
        )


def test_llm_harness_proposer_builds_prompt_payload_and_returns_generated_patch(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    captured: dict[str, object] = {}

    def fake_run(command, payload, effective_config):
        captured["command"] = command
        captured["payload"] = payload
        captured["effective_config"] = effective_config
        return {
            "proposal": {
                "strategy": "llm_harness_patch",
                "summary": "raise retrieval breadth",
            },
            "config_patch": {"retrieval": {"top_k": 12}},
            "notes": "generated by llm harness",
        }

    monkeypatch.setattr(
        "meta_harness.proposers.llm_harness_proposer.run_proposal_command",
        fake_run,
    )

    proposer = LLMHarnessProposer(
        command=["python", "scripts/generate.py"],
        model_name="gpt-test",
        system_prompt="You are an optimizer.",
    )
    payload = proposer.propose(
        objective={
            "goal": "improve retrieval robustness",
            "focus": "retrieval",
        },
        experience={
            "matching_runs": [{"run_id": "run-1"}, {"run_id": "run-2"}],
            "failure_records": [
                {"run_id": "run-1", "family": "timeout"},
                {"run_id": "run-2", "family": "timeout"},
            ],
            "best_candidate": {"candidate_id": "cand-best"},
        },
        constraints={
            "profile_name": "base",
            "project_name": "demo",
            "proposal_constraints": {
                "allowed_scopes": ["retrieval", "budget"],
                "blocked_scopes": ["system_prompt"],
                "failure_family_priority": ["timeout"],
            },
            "effective_config": {
                "optimization": {
                    "llm_harness": {
                        "command": ["python", "scripts/generate.py"],
                        "model": "gpt-test",
                    }
                },
                "budget": {"max_turns": 12},
            },
        },
    )

    assert captured["command"] == ["python", "scripts/generate.py"]
    prompt_payload = captured["payload"]
    assert prompt_payload["model"] == "gpt-test"
    assert prompt_payload["profile"] == "base"
    assert prompt_payload["project"] == "demo"
    assert prompt_payload["proposal_constraints"]["allowed_scopes"] == ["retrieval", "budget"]
    assert prompt_payload["proposal_constraints"]["blocked_scopes"] == ["system_prompt"]
    assert "improve retrieval robustness" in prompt_payload["user_prompt"]
    assert "run-1" in prompt_payload["user_prompt"]
    assert "cand-best" in prompt_payload["user_prompt"]
    assert "allowed_scopes" in prompt_payload["user_prompt"]
    assert payload["proposer_kind"] == "llm_harness"
    assert payload["proposal"]["strategy"] == "llm_harness_patch"
    assert payload["config_patch"] == {"retrieval": {"top_k": 12}}
    assert payload["source_run_ids"] == ["run-1", "run-2"]
