from __future__ import annotations

import json
import sys
from typing import Any


def _load_payload() -> dict[str, Any]:
    raw = sys.stdin.read().strip()
    if not raw:
        return {}
    data = json.loads(raw)
    return data if isinstance(data, dict) else {}


def _source_run_ids(experience: dict[str, Any]) -> list[str]:
    matching_runs = experience.get("matching_runs")
    if not isinstance(matching_runs, list):
        return []
    return [
        str(item.get("run_id"))
        for item in matching_runs
        if isinstance(item, dict) and str(item.get("run_id") or "")
    ]


def _failure_families(experience: dict[str, Any]) -> list[str]:
    failure_records = experience.get("failure_records")
    if not isinstance(failure_records, list):
        return []
    families: list[str] = []
    for item in failure_records:
        if not isinstance(item, dict):
            continue
        family = str(item.get("family") or item.get("signature") or "").strip()
        if family:
            families.append(family)
    return families


def _build_config_patch(
    *,
    focus: str,
    effective_config: dict[str, Any],
    failure_families: list[str],
) -> dict[str, Any]:
    patch: dict[str, Any] = {}

    retrieval = effective_config.get("retrieval")
    if focus in {"retrieval", "all"}:
        current_top_k = (
            int(retrieval.get("top_k", 8)) if isinstance(retrieval, dict) else 8
        )
        patch["retrieval"] = {
            "top_k": current_top_k + 4,
        }

    if focus == "memory":
        patch["memory"] = {"enabled": True, "max_items": 24}

    if focus == "indexing":
        patch["indexing"] = {"enabled": True, "refresh": "on_failure"}

    timeout_count = sum(1 for item in failure_families if item == "timeout")
    if timeout_count >= 2:
        budget = effective_config.get("budget")
        current_turns = int(budget.get("max_turns", 12)) if isinstance(budget, dict) else 12
        patch["budget"] = {"max_turns": current_turns + 2}

    return patch


def build_proposal(payload: dict[str, Any]) -> dict[str, Any]:
    objective = payload.get("objective")
    experience = payload.get("experience")
    effective_config = payload.get("effective_config")
    objective = objective if isinstance(objective, dict) else {}
    experience = experience if isinstance(experience, dict) else {}
    effective_config = effective_config if isinstance(effective_config, dict) else {}

    focus = str(objective.get("focus") or "all")
    model = str(payload.get("model") or "unknown-model")
    source_runs = _source_run_ids(experience)
    failure_families = _failure_families(experience)
    best_candidate = experience.get("best_candidate")
    best_candidate_id = (
        str(best_candidate.get("candidate_id"))
        if isinstance(best_candidate, dict) and str(best_candidate.get("candidate_id") or "")
        else None
    )
    config_patch = _build_config_patch(
        focus=focus,
        effective_config=effective_config,
        failure_families=failure_families,
    )

    proposal = {
        "strategy": "llm_harness_patch",
        "model": model,
        "focus": focus,
        "summary": f"example llm harness proposal for {focus}",
        "source_runs": source_runs,
        "failure_families": failure_families[:5],
    }
    if best_candidate_id is not None:
        proposal["baseline_candidate_id"] = best_candidate_id

    return {
        "proposal": proposal,
        "config_patch": config_patch,
        "notes": f"generated by llm harness example script using {model}",
    }


def main() -> int:
    payload = _load_payload()
    result = build_proposal(payload)
    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
